apiVersion: v1
kind: Service
metadata:
  labels:
    app: wil-playground
  name: wil-playground
  namespace: dev
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8888
  selector:
    app: wil-playground