apiVersion: v1
kind: Service
metadata:
  name: wil42-service
spec:
  type: NodePort
  selector:
    app: wil42
  ports:
    - protocol: TCP
      port: 9999
      targetPort: 9999
      nodePort: 31000