apiVersion: v1
kind: Service
metadata:
  name: wil42-service
spec:
  selector:
    app: wil42
  type: NodePort
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8081
      nodePort: 31000